name: Auto Renew Tickhosting

on:
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'
  workflow_dispatch:

jobs:
  Auto_renew_tickhosting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run auto renew script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python auto_renew.py

